todo_auth/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from todo_auth.forms import AuthForm
from todo_auth.views import RegistrationView

urlpatterns = [
    url(r'^login$',
        auth_views.login,
        {'template_name': 'todo_auth/login.html', 'authentication_form': AuthForm},
        name='login'),
    url(r'^registration', RegistrationView.as_view(), name='registration'),
    url(r'^logout$', auth_views.logout, name='logout')
]

todo_manage/urls.py
from django.conf.urls import url
from django.conf.urls.static import static

from todo_manage.views import TodoListView, TodoDeleteView, TodoDoneView, TodoCreateView, TodoUpdateView
from todoapp import settings

urlpatterns = [
                  url(r'^$', TodoListView.as_view(), name='list'),
                  url(r'^add$', TodoCreateView.as_view(), name='add'),
                  url(r'^edit/(?P<pk>[0-9]+)$', TodoUpdateView.as_view(), name='edit'),
                  url(r'^delete/(?P<pk>[0-9]+)$', TodoDeleteView.as_view(), name='delete'),
                  url(r'^done/(?P<pk>[0-9]+)$', TodoDoneView.as_view(), name='done')
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todoapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from todoapp.views import index_view

urlpatterns = [
    url(r'^$', index_view),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('todo_auth.urls', namespace='Account')),
    url(r'^manage/', include('todo_manage.urls', namespace='Todo'))
]

todo_manage/models.py
from django.contrib.auth.models import User
from django.db import models


class TodoQuerySet(models.QuerySet):
    def active(self):
        return self.filter(status='UNDONE')


class Todo(models.Model):
    TODO_STATUSES = (
        ('DONE', 'Done'),
        ('UNDONE', 'Undone'),
    )

    user = models.ForeignKey(User)
    name = models.CharField(max_length=100)
    description = models.TextField()
    status = models.CharField(choices=TODO_STATUSES, default='UNDONE', max_length=6)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    objects = TodoQuerySet.as_manager()

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return 'Task #' + str(self.id)

    def is_done(self):
        return self.status == 'DONE'

    def mark_as_done(self, user=None):
        self.status = 'DONE'
        if hasattr(self, 'related_done'):
            self.related_done.user = user
        else:
            TodoDone.objects.create(todo=self, user=user)
        self.save()


class TodoDone(models.Model):
    todo = models.OneToOneField(Todo, related_name='related_done')
    user = models.ForeignKey(User)
    updated_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

todo_auth/forms.py
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django import forms


class AuthForm(AuthenticationForm):
    username = UsernameField(
        max_length=254,
        widget=forms.TextInput(attrs={'class': 'form-control', 'autofocus': ''}),
    )
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )


class RegistrationForm(UserCreationForm):
    username = UsernameField(
        max_length=254,
        widget=forms.TextInput(attrs={'class': 'form-control', 'autofocus': ''}),
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        strip=False,
        help_text="Enter the same password as before, for verification.",
    )

todo_manage/forms.py
from django import forms

from todo_manage.models import Todo


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['name', 'description', 'status']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'rows': 4, 'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control col-sm-4'})
        }

todo_auth/views.py
from django.contrib.auth import login
from django.shortcuts import redirect
from django.views.generic import FormView

from todo_auth.forms import RegistrationForm


class RegistrationView(FormView):
    form_class = RegistrationForm
    template_name = 'todo_auth/registration.html'

    def get_success_url(self):
        return '/'

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            login(self.request, form.instance)
            return redirect(self.get_success_url())

todo_manage/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from todo_manage.forms import TodoForm
from todo_manage.models import Todo


class TodoListView(LoginRequiredMixin, ListView):
    template_name = 'todo_manage/todo_list.html'
    paginate_by = 5

    def get_queryset(self):
        queryset = Todo.objects.all()
        target_filter = self.request.session.get('filter')
        if target_filter == 'active':
            queryset = queryset.active()
        return queryset

    def get(self, request, *args, **kwargs):
        target_filter = self.request.GET.get('filter')
        if target_filter:
            request.session['filter'] = target_filter
        return super(TodoListView, self).get(self, request, *args, **kwargs)


class TodoFormView(LoginRequiredMixin):
    form_class = TodoForm
    template_name = 'todo_manage/todo_form.html'

    def __init__(self):
        self.request = None

    def get_success_url(self):
        return reverse('Todo:list')

    def get_queryset(self):
        return Todo.objects.all().filter(user=self.request.user)

    def form_valid(self, form):
        form.save(commit=False)
        form.instance.user = self.request.user
        save_result = super(TodoFormView, self).form_valid(form)
        if form.instance.is_done():
            form.instance.mark_as_done(self.request.user)
        return save_result


class TodoCreateView(TodoFormView, CreateView):
    pass


class TodoUpdateView(TodoFormView, UpdateView):
    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            messages.warning(request, 'Todo #' + kwargs.get('pk') + ' was not found for editing.')
            return redirect(reverse('Todo:list'))
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class TodoDeleteView(LoginRequiredMixin, DeleteView):
    def get_success_url(self):
        return reverse('Todo:list')

    def get_queryset(self):
        return Todo.objects.all().filter(user=self.request.user)


class TodoDoneView(LoginRequiredMixin, View):
    queryset = Todo.objects.all()

    def get(self, request, pk=None):
        try:
            self.queryset.get(pk=pk).mark_as_done(user=self.request.user)
            messages.success(request, 'Todo #' + pk + ' has been marked as Done.')
            return redirect(reverse('Todo:list'))
        except Todo.DoesNotExist:
            messages.warning(request, 'Todo #' + pk + ' was not found.')
            return redirect(reverse('Todo:list'))

todoapp/views.py
from django.shortcuts import redirect
from django.urls import reverse


def index_view(request):
    if request.user:
        redirect_url = reverse('Todo:list')
    else:
        redirect_url = reverse('Account:login')

    return redirect(redirect_url)

todo_auth/templates/todo_auth/layout.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
          integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'todo_auth/styles.css' %}">

</head>
<body>

<div class="container">
    <div class="header">
        <h1 class="text-center">DJANGO TODO</h1>
        <hr/>
    </div>

    {% block content %}{% endblock %}
</div>
</body>
</html>

todo_auth/templates/todo_auth/login.html
{% extends 'todo_auth/layout.html' %}

{% block content %}
    <div class="col-sm-4 offset-sm-4">
        <form class="form__auth" method="POST">
            {% csrf_token %}


            <h2>Login:</h2>
            <hr/>

            {% for field in form %}
                <div class="form-group">
                    <label>{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}

            {% if form.non_field_errors %}
                <div class="alert alert-warning pb-0">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <div class="text-center">
                <p>
                    <button class="btn btn-outline-primary" type="submit">Login</button>
                </p>
                <p>or</p>
                <a href="{% url 'Account:registration' %}">Registration</a>
            </div>
        </form>
    </div>
{% endblock %}

todo_auth/templates/todo_auth/registration.html
{% extends 'todo_auth/layout.html' %}

{% block content %}
    <div class="col-sm-4 offset-sm-4">
        <form class="form__auth" method="POST">
            {% csrf_token %}

            <h2>New user:</h2>
            <hr/>

            {% for field in form %}
                <div class="form-group">
                    <label>{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}

            {% if form.non_field_errors %}
                <div class="alert alert-warning pb-0">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            {% if form.errors %}
                <div class="alert alert-warning pb-0">
                    {{ form.errors }}
                </div>
            {% endif %}


            <div class="text-center">
                <p>
                    <button class="btn btn-outline-primary" type="submit">Register</button>
                </p>
                <p>or</p>
                <a href="{% url 'Account:login' %}">Login</a>
            </div>
        </form>
    </div>
{% endblock %}

todo_manage/templates/manage_layout.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
          integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>

<div class="container">
    <div class="header">
        <h1 class="text-center">DJANGO TODO</h1>
        <div class="text-right">
            <strong>User:</strong> {{ user }}
            <a href="{% url 'Account:logout' %}">[ Logout ]</a>
        </div>
        <hr/>
    </div>

    {% block content %}{% endblock %}
</div>
</body>
</html>

todo_manage/templates/todo_manage/todo_confirm_delete.html
{% extends 'manage_layout.html' %}

{% block content %}
    <form method="post">{% csrf_token %}

        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirm Dialog</h5>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete "{{ object }}"?</p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Delete</button>
                    <a href="{% url 'Todo:list' %}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                </div>
            </div>
        </div>

    </form>
{% endblock %}

todo_manage/templates/todo_manage/todo_form.html
{% extends 'manage_layout.html' %}

{% block content %}
    <div class="row">
        <h2 class="col-sm-6">
            {% if not form.instance.id %}
                Add Todo
            {% else %}
                Edit Todo
            {% endif %}
        </h2>
        <div class="col-sm-6 text-right">
            <a class="btn btn-outline-primary" href="{% url 'Todo:list' %}">Todo List</a>
        </div>
    </div>

    <form method="post" class="todo__form">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="text-center">
            <button type="submit" class="btn btn-outline-primary">Save</button>
        </div>
    </form>
{% endblock %}

todo_manage/templates/todo_manage/todo_list.html
{% extends 'manage_layout.html' %}

{% block content %}
    <div class="row" xmlns="http://www.w3.org/1999/html">
        <h2 class="col-xs-12 col-sm-4">Todo list</h2>
        <div class="col-xs-12 col-sm-8 text-center text-sm-right">
            {% if request.session.filter == 'active' %}
                <a class="btn btn-outline-primary" href="{% url 'Todo:list' %}?filter=all">Show All tasks</a>
            {% else %}
                <a class="btn btn-outline-primary" href="{% url 'Todo:list' %}?filter=active">Hide Completed
                    tasks</a>
            {% endif %}
            <a class="btn btn-outline-primary" href="{% url 'Todo:add' %}">Add</a>
        </div>
    </div>

    {% if messages %}
        {% for message in messages %}
            <div class="mt-2 alert {% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">
                <strong>Last action:</strong> {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="col-12 mt-2">
        {% for task in object_list %}
            <div class="row todo__list__todo ">
                <div class="col-sm-9">
                    <div class="col-12 mt-1 p-2 pl-3"
                         style="overflow:hidden; border-bottom: 1px dashed #bcbcbc">
                        <strong>#{{ task.id }}</strong>
                        <nobr>by <strong>{{ task.user.username|upper }}</strong></nobr>
                        <nobr>at <strong>{{ task.created_at|date:'d M. H:i' }}</strong></nobr>
                    </div>
                    <div class="col-12 todo__title p-3 pb-0">
                        {{ task.name }}
                    </div>
                    <div class="col-12 todo__description">
                        {{ task.description|linebreaks }}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="col-12 mt-2">
                        <div class="row">

                            {% if task.user == user %}
                                <a class="col-6 btn btn-outline-primary"
                                   href="{% url 'Todo:edit' task.id %}">Edit</a>
                                <a class="col-6 btn btn-outline-info"
                                   href="{% url 'Todo:delete' task.id %}">Delete</a>
                            {% endif %}

                            {% if task.is_done %}
                                <div class="col-12 mt-2">
                                    <strong>Done</strong>
                                    <nobr>by <strong>{{ task.related_done.user }}</strong></nobr>
                                    <nobr>at <strong>{{ task.related_done.updated_at }}</strong></nobr>
                                </div>
                            {% else %}
                                <a class="col-12 mb-2 mt-2 btn btn-success" href="{% url 'Todo:done' task.id %}">
                                    Mark Done</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="alert alert-info text-center">No tasks yet.</div>
        {% endfor %}
    </div>

    {% if is_paginated %}
        <nav>
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                    </li>
                {% endif %}
                <li class="page-item"><a class="page-link">Page {{ page_obj.number }}
                    of {{ page_obj.paginator.num_pages }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}

{% endblock %}